spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybatis-plus?characterEncoding=utf8&useSSL=false
    username: root
    password: root
  cache:
    redis:
      timeToLive: 100
  redis:
    port: 6379
    host: localhost
    lettuce:
      pool:
      #最大连接数
        max-active: 8
    #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
    #最大空闲
        max-idle: 8
    #最小空闲
        min-idle: 0
  #连接超时时间
        timeout: 10000

#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations:  classpath:/mapper/*Mapper.xml,classpath:/com/lianglong/cache/mapper/*/*Mapper.xml
  type-aliases-package: com.lianglong.cache.entity
server:
  port: 8080
---
server:
  port: 2001
spring:
  profiles: dev
---
server:
  port: 2002
spring:
  profiles: permission